# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic (*sub-namespace, see below)
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

twist_mux_1:
  ros__parameters:
    topics:
      navigation:
        # topic   : /cmd_vel_des
        topic   : /cmd_vel_mux/cmd_vel_safety
        timeout : 1.0
        priority: 10
      joystick:
        topic   : /cmd_vel_mux/joystick_controller
        timeout : 0.5
        priority: 20
